### ISSUE TITLE
current_team helper isn't available in controllers

### ISSUE THREAD

**Issue by neiljohari** [VolunteerLiveTeam/lively#3]
Using `helper_method` in application_controller.rb should make it possible to use in controllers as well as views (at least that's [how devise does it](https://github.com/plataformatec/devise/blob/master/lib/devise/controllers/helpers.rb)).

**Comment by kailan** [comment]
In `team-management`, I removed the helper and replaced it with a variable that gets set for every request to allow the team to be cached per-request.

https://github.com/VolunteerLiveTeam/lively/blob/team-management/app/controllers/application_controller.rb#L15-L19

**Comment by kailan** [comment]
Fixed in #4.
